name = "story-server"
main = "worker.js"
compatibility_date = "2024-01-01"

# After running: npx wrangler kv:namespace create STORIES
# Replace the ID below with the one you receive
kv_namespaces = [
  { binding = "STORIES", id = "118d2dec0aba4a7e973b69f4d8c0cc1b" }
]
