// js/wordData.js
// Данные для викторины "Слова" – 3 уровня по 30 вопросов
// Уровень 1: слова из 2 хирагана
// Уровень 2: слова из 3 хирагана
// Уровень 3: слова из 4 хирагана

const WORD_LEVELS = {
  1: {
    title: 'Уровень 1 (2 буквы)',
    questions: [
      { question: "あい", options: ["любовь", "собака", "кот", "дом"], correct: 0, explanation: "あい = любовь" },
      { question: "うえ", options: ["верх", "низ", "право", "лево"], correct: 0, explanation: "うえ = верх" },
      { question: "おおい", options: ["большой", "маленький", "быстрый", "медленный"], correct: 0, explanation: "おおい = большой" },
      { question: "かお", options: ["лицо", "рука", "нога", "глаз"], correct: 0, explanation: "かお = лицо" },
      { question: "きく", options: ["слушать", "говорить", "читать", "писать"], correct: 0, explanation: "きく = слушать" },
      { question: "こえ", options: ["голос", "шум", "тишина", "песня"], correct: 0, explanation: "こえ = голос" },
      { question: "さけ", options: ["лосось", "тунец", "угорь", "креветка"], correct: 0, explanation: "さけ = лосось" },
      { question: "しろい", options: ["белый", "чёрный", "красный", "синий"], correct: 0, explanation: "しろい = белый" },
      { question: "すし", options: ["суши", "сашими", "рамэн", "удон"], correct: 0, explanation: "すし = суши" },
      { question: "せき", options: ["кашель", "чихание", "головная боль", "жар"], correct: 0, explanation: "せき = кашель" },
      { question: "そら", options: ["небо", "море", "гора", "река"], correct: 0, explanation: "そら = небо" },
      { question: "たけ", options: ["бамбук", "дерево", "цветок", "трава"], correct: 0, explanation: "たけ = бамбук" },
      { question: "ちち", options: ["отец", "мать", "брат", "сестра"], correct: 0, explanation: "ちち = отец" },
      { question: "つき", options: ["луна", "солнце", "звезда", "облако"], correct: 0, explanation: "つき = луна" },
      { question: "てん", options: ["небо", "земля", "вода", "огонь"], correct: 0, explanation: "てん = небо (как элемент)" },
      { question: "とり", options: ["птица", "рыба", "насекомое", "зверь"], correct: 0, explanation: "とり = птица" },
      { question: "なか", options: ["внутри", "снаружи", "рядом", "далеко"], correct: 0, explanation: "なか = внутри" },
      { question: "にし", options: ["запад", "восток", "север", "юг"], correct: 0, explanation: "にし = запад" },
      { question: "ぬの", options: ["ткань", "бумага", "дерево", "металл"], correct: 0, explanation: "ぬの = ткань" },
      { question: "ねこ", options: ["кот", "собака", "мышь", "птица"], correct: 0, explanation: "ねこ = кот" },
      { question: "はな", options: ["цветок", "нос", "рука", "глаз"], correct: 0, explanation: "はな = цветок (или нос, но здесь цветок)" },
      { question: "ひろ", options: ["широкий", "узкий", "длинный", "короткий"], correct: 0, explanation: "ひろ = широкий" },
      { question: "ふね", options: ["корабль", "машина", "самолёт", "поезд"], correct: 0, explanation: "ふね = корабль" },
      { question: "へや", options: ["комната", "дом", "школа", "парк"], correct: 0, explanation: "へや = комната" },
      { question: "ほし", options: ["звезда", "луна", "солнце", "облако"], correct: 0, explanation: "ほし = звезда" },
      { question: "まち", options: ["город", "деревня", "страна", "мир"], correct: 0, explanation: "まち = город" },
      { question: "みち", options: ["дорога", "река", "гора", "лес"], correct: 0, explanation: "みち = дорога" },
      { question: "むし", options: ["насекомое", "птица", "рыба", "зверь"], correct: 0, explanation: "むし = насекомое" },
      { question: "めが", options: ["очки", "глаза", "брови", "ресницы"], correct: 0, explanation: "めが = очки" },
      { question: "もり", options: ["лес", "поле", "сад", "парк"], correct: 0, explanation: "もり = лес" }
    ]
  },
  2: {
    title: 'Уровень 2 (3 буквы)',
    questions: [
      { question: "あおい", options: ["синий", "зелёный", "жёлтый", "фиолетовый"], correct: 0, explanation: "あおい = синий" },
      { question: "あさひ", options: ["утреннее солнце", "закат", "полдень", "ночь"], correct: 0, explanation: "あさひ = утреннее солнце" },
      { question: "いのち", options: ["жизнь", "смерть", "здоровье", "счастье"], correct: 0, explanation: "いのち = жизнь" },
      { question: "うみの", options: ["морской", "небесный", "горный", "речной"], correct: 0, explanation: "うみの = морской" },
      { question: "えいが", options: ["кино", "театр", "книга", "музыка"], correct: 0, explanation: "えいが = кино" },
      { question: "おにぎ", options: ["онигири", "суши", "сашими", "бенто"], correct: 0, explanation: "おにぎ = онигири (рисовый шарик)" },
      { question: "かぜの", options: ["ветреный", "дождливый", "снежный", "солнечный"], correct: 0, explanation: "かぜの = ветреный" },
      { question: "きょう", options: ["сегодня", "вчера", "завтра", "сейчас"], correct: 0, explanation: "きょう = сегодня" },
      { question: "くもり", options: ["облачно", "ясно", "дождливо", "ветрено"], correct: 0, explanation: "くもり = облачно" },
      { question: "こころ", options: ["сердце", "душа", "мысль", "чувство"], correct: 0, explanation: "こころ = сердце (душа)" },
      { question: "さくら", options: ["сакура", "слива", "персик", "яблоня"], correct: 0, explanation: "さくら = сакура" },
      { question: "しんご", options: ["Синго (имя)", "знак", "сигнал", "язык"], correct: 0, explanation: "しんご = Синго (имя, может означать 'знак')" },
      { question: "すずめ", options: ["воробей", "голубь", "ворона", "ласточка"], correct: 0, explanation: "すずめ = воробей" },
      { question: "せかい", options: ["мир", "вселенная", "земля", "космос"], correct: 0, explanation: "せかい = мир" },
      { question: "そよか", options: ["лёгкий ветерок", "ураган", "шторм", "бриз"], correct: 0, explanation: "そよか = лёгкий ветерок" },
      { question: "たまご", options: ["яйцо", "овощ", "фрукт", "мясо"], correct: 0, explanation: "たまご = яйцо" },
      { question: "ちから", options: ["сила", "энергия", "мощь", "воля"], correct: 0, explanation: "ちから = сила" },
      { question: "つばめ", options: ["ласточка", "воробей", "соловей", "синица"], correct: 0, explanation: "つばめ = ласточка" },
      { question: "てがみ", options: ["письмо", "открытка", "газета", "журнал"], correct: 0, explanation: "てがみ = письмо" },
      { question: "とんぼ", options: ["стрекоза", "бабочка", "пчела", "муха"], correct: 0, explanation: "とんぼ = стрекоза" },
      { question: "なみだ", options: ["слеза", "капля", "дождь", "роса"], correct: 0, explanation: "なみだ = слеза" },
      { question: "にほん", options: ["Япония", "Китай", "Корея", "Тайвань"], correct: 0, explanation: "にほん = Япония" },
      { question: "ぬいぐ", options: ["плюшевый (мишка)", "мягкий", "пушистый", "тёплый"], correct: 0, explanation: "ぬいぐ (от ぬいぐるみ = плюшевая игрушка)" },
      { question: "ねむり", options: ["сон", "ява", "отдых", "работа"], correct: 0, explanation: "ねむり = сон" },
      { question: "はなび", options: ["фейерверк", "цветок", "огонь", "свет"], correct: 0, explanation: "はなび = фейерверк" },
      { question: "ひかり", options: ["свет", "тень", "луч", "блеск"], correct: 0, explanation: "ひかり = свет" },
      { question: "ふゆの", options: ["зимний", "летний", "весенний", "осенний"], correct: 0, explanation: "ふゆの = зимний" },
      { question: "へいわ", options: ["мир", "война", "спокойствие", "хаос"], correct: 0, explanation: "へいわ = мир (спокойствие)" },
      { question: "ほのお", options: ["пламя", "огонь", "искра", "дым"], correct: 0, explanation: "ほのお = пламя" },
      
       { question: "へいき", options: ["спокойный", "беспокойный", "тихий", "громкий"], correct: 0, explanation: "へいき = спокойный" },
    ]
  },
  3: {
    title: 'Уровень 3 (4 буквы)',
    questions: [
      { question: "あいして", options: ["люблю", "ненавижу", "обижаю", "жалею"], correct: 0, explanation: "あいして = люблю" },
      { question: "あさがお", options: ["вьюнок", "роза", "тюльпан", "лилия"], correct: 0, explanation: "あさがお = вьюнок (утренняя слава)" },
      { question: "いちごの", options: ["клубничный", "яблочный", "вишнёвый", "лимонный"], correct: 0, explanation: "いちごの = клубничный" },
      { question: "うたがわ", options: ["песенное (что-то)", "танцевать", "музыка", "поэзия"], correct: 0, explanation: "うたがわ = песенный (от うた)" },
      { question: "えんぴつ", options: ["карандаш", "ручка", "кисть", "мел"], correct: 0, explanation: "えんぴつ = карандаш" },
      { question: "おはよう", options: ["доброе утро", "добрый день", "добрый вечер", "спокойной ночи"], correct: 0, explanation: "おはよう = доброе утро" },
      { question: "かきごり", options: ["колотый лёд с сиропом", "мороженое", "сорбет", "коктейль"], correct: 0, explanation: "かきごり = колотый лёд с сиропом" },
      { question: "きょうと", options: ["Киото", "Токио", "Осака", "Нагоя"], correct: 0, explanation: "きょうと = Киото" },
      { question: "くうきの", options: ["воздушный", "водный", "земной", "огненный"], correct: 0, explanation: "くうきの = воздушный" },
      { question: "けしごむ", options: ["ластик", "точилка", "линейка", "клей"], correct: 0, explanation: "けしごむ = ластик" },
      { question: "こんにち", options: ["привет", "здравствуйте", "до свидания", "извините"], correct: 0, explanation: "こんにち = привет (сокращённое)" },
      { question: "さくらん", options: ["вишня (цвет)", "сакура", "слива", "персик"], correct: 0, explanation: "さくらん = вишнёвый (цвет)" },
      { question: "しんかん", options: ["Синкан (буддийский)", "новый", "старый", "быстрый"], correct: 0, explanation: "しんかん = Синкан (может означать 'новый')" },
      { question: "すいかん", options: ["арбузный", "дынный", "тыквенный", "огуречный"], correct: 0, explanation: "すいかん = арбузный" },
      { question: "せんぱい", options: ["старший (по статусу)", "младший", "учитель", "ученик"], correct: 0, explanation: "せんぱい = старший (по статусу)" },
      { question: "そらまめ", options: ["конские бобы", "горох", "фасоль", "соя"], correct: 0, explanation: "そらまめ = конские бобы" },
      { question: "たんごの", options: ["словарный", "грамматический", "фонетический", "лексический"], correct: 0, explanation: "たんごの = словарный" },
      { question: "ちきゅう", options: ["Земля", "Марс", "Венера", "Юпитер"], correct: 0, explanation: "ちきゅう = Земля (планета)" },
      { question: "つくえ", options: ["письменный (стол)", "кухонный", "обеденный", "журнальный"], correct: 0, explanation: "つくえ = письменный (стол)" },
      { question: "てんきよ", options: ["прогноз погоды", "погода", "климат", "температура"], correct: 0, explanation: "てんきよ = прогноз погоды (сокращ.)" },
      { question: "とんかつ", options: ["свиная отбивная", "курица", "рыба", "говядина"], correct: 0, explanation: "とんかつ = свиная отбивная" },
      { question: "なつやす", options: ["летние каникулы", "зимние каникулы", "весенние каникулы", "осенние каникулы"], correct: 0, explanation: "なつやす = летние каникулы" },
      { question: "にんげん", options: ["человек", "животное", "робот", "бог"], correct: 0, explanation: "にんげん = человек" },
      { question: "ぬいぐる", options: ["плюшевая игрушка", "кукла", "мяч", "конструктор"], correct: 0, explanation: "ぬいぐる = плюшевая игрушка" },
      { question: "ねんどろ", options: ["глиняный", "керамический", "пластиковый", "металлический"], correct: 0, explanation: "ねんどろ = глиняный" },
      { question: "はがき", options: ["открытка", "конверт", "бумага", "конверт"], correct: 0, explanation: "はがき = открытка" },
      { question: "ひるごは", options: ["обед", "завтрак", "ужин", "полдник"], correct: 0, explanation: "ひるごは = обед (сокращ. от ひるごはん)" },
      { question: "ふゆやす", options: ["зимние каникулы", "летние каникулы", "весенние каникулы", "осенние каникулы"], correct: 0, explanation: "ふゆやす = зимние каникулы" },
      { question: "まいにち", options: ["каждый день", "каждую ночь", "каждую неделю", "каждый месяц"], correct: 0, explanation: "まいにち = каждый день)" },
      { question: "ほんやく", options: ["перевод", "переводчик", "словарь", "текст"], correct: 0, explanation: "ほんやく = перевод" }
    ]
  }
};