import { List } from 'immutable';

// Строго оригинальная структура данных, которую ждут компоненты звука, часов и динозаврика
const i18n = {
     "lan": ["ar", "az", "be", "bg", "ca", "cs", "de", "en", "es", "fa", "fr", "he", "hi", "hu", "hy", "id", "it", "ja", "ka", "kk", "nl", "pl", "pt", "ro", "ru", "sk", "sr", "th", "tk", "tr", "uk", "uz", "vi", "zh"],
  "default": "ru",
  "data": {
"bonus": {
  "ru": "Бонус",
  "en": "Bonus",
  "ar": "مكافأة",
  "az": "Bonus",
  "be": "Бонус",
  "bg": "Бонус",
  "ca": "Bonus",
  "cs": "Bonus",
  "de": "Bonus",
  "es": "Bonus",
  "fa": "پاداش",
  "fr": "Bonus",
  "he": "בונוס",
  "hi": "बोनस",
  "hu": "Bónusz",
  "hy": "Բոնուս",
  "id": "Bonus",
  "it": "Bonus",
  "ja": "ボーナス",
  "ka": "ბონუსი",
  "kk": "Бонус",
  "nl": "Bonus",
  "pl": "Bonus",
  "pt": "Bônus",
  "ro": "Bonus",
  "sk": "Bonus",
  "sr": "Бонус",
  "th": "โบนัส",
  "tk": "Bonus",
  "tr": "Bonus",
  "uk": "Бонус",
  "uz": "Bonus",
  "vi": "Tiền thưởng",
  "zh": "奖励"
},

"leaderboard": {
    "ar": "قمة",
    "az": "Top",
    "be": "Топ",
    "bg": "Топ",
    "ca": "Top",
    "cs": "Top",
    "de": "Top",
    "en": "Top",
    "es": "Top",
    "fa": "برتر",
    "fr": "Top",
    "he": "צמרת",
    "hi": "टॉप",
    "hu": "Top",
    "hy": "Թոփ",
    "id": "Puncak",
    "it": "Top",
    "ja": "トップ",
    "ka": "ტოპ",
    "kk": "Топ",
    "nl": "Top",
    "pl": "Top",
    "pt": "Top",
    "ro": "Top",
    "ru": "Топ",
    "sk": "Top",
    "sr": "Топ",
    "th": "ยอด",
    "tk": "Top",
    "tr": "Zirve",
    "uk": "Топ",
    "uz": "Top",
    "vi": "Đỉnh",
    "zh": "榜首"
},
"leaderboardTitle": {  "ar": "أفضل 10 لاعبين", "az": "TOP-10 OYUNÇU", "be": "ТОП-10 ГУЛЬЦОЎ", "bg": "ТОП 10 ИГРАЧИ",
  "ca": "TOP-10 JUGADORS", "cs": "TOP 10 HRÁČŮ", "de": "TOP 10 SPIELER", "en": "TOP 10 PLAYERS",
  "es": "TOP 10 JUGADORES", "fa": "۱۰ بازیکن برتر", "fr": "TOP 10 JOUEURS", "he": "טופ 10 שחקנים",
  "hi": "शीर्ष 10 खिलाड़ी", "hu": "TOP 10 JÁTÉKOS", "hy": "ԼԱՎԱԳՈՒՅՆ 10 ԽԱՂԱՑՈՂՆԵՐ", "id": "10 PEMAIN TERATAS",
  "it": "TOP 10 GIOCATORI", "ja": "トップ10プレイヤー", "ka": "ტოპ 10 მოთამაშე", "kk": "ҮЗДІК 10 ОЙЫНШЫ", "nl": "TOP 10 SPELERS",
  "pl": "TOP 10 GRACZY", "pt": "TOP 10 JOGADORES", "ro": "TOP 10 JUCĂTORI", "ru": "ТОП-10 ИГРОКОВ",
  "sk": "TOP 10 HRÁČOV", "sr": "ТОП 10 ИГРАЧА", "th": "10 อันดับผู้เล่นสูงสุด", "tk": "TOP-10 OÝUNÇY",
  "tr": "EN İYİ 10 OYUNCU", "uk": "ТОП-10 ГРАВЦІВ", "uz": "YETAKCHI 10 O'YINCHI", "vi": "TOP 10 NGƯỜI CHƠI",
  "zh": "前10名玩家"},


  "leaderboardOffline": {"ar": "قوائم المتصدرين غير متوفرة بدون إنترنت.", "az": "Liderlər siyahısı şəbəkəsiz mövcud deyil.",
  "be": "Спісы лідараў недаступныя без сеткі.", "bg": "Класациите не са достъпні без мрежа.",
  "ca": "Les taules de classificació no estan disponibles sense xarxa.", "cs": "Žebříčky nejsou bez sítě dostupné.",
  "de": "Bestenlisten sind ohne Netzwerk nicht verfügbar.", "en": "Leaderboards are unavailable offline.",
  "es": "Las tablas de clasificación no están disponibles sin red.", "fa": "جدول امتیازات بدون شبکه در دسترس نیست.",
  "fr": "Les classements ne sont pas disponibles sans réseau.", "he": "לוחות המובילים אינם זמינים ללא רשת.",
  "hi": "लीडरबोर्ड नेटवर्क के बिना उपलब्ध नहीं हैं।", "hu": "A ranglisták hálózat nélkül nem érhetők el.",
  "hy": "Առաջատարների աղյուսակները հասանելի չեն առանց ցանցի:", "id": "Papan peringkat tidak tersedia tanpa jaringan.",
  "it": "I tabelloni dei leader no sono disponibili senza rete.",   "ja": "リーダーボードはオフラインでは利用できません。", "ka": "ლიდერბორდები მიუწვდომელია ქსელის გარეშე.",
  "kk": "Лидербордтар желісіз қолжетімді емес.", "nl": "Ranglijsten zijn offline niet beschikbaar.",
  "pl": "Tabele liderów są niedostępne bez sieci.", "pt": "As tabelas de classificação não estão disponíveis offline.",
  "ro": "Clasamentele nu sunt disponibile fără rețea.", "ru": "Списки лидеров недоступны без сети.",
  "sk": "Rebríčky nie son bez siete dostupné.", "sr": "Табеле лидер у офлајн режиму нису доступне.",
  "th": "กระดานผู้นำไม่พร้อมใช้งานแบบออฟไลน์", "tk": "Liderler sanawy şansyz elýeterli däl.",
  "tr": "Liderlik tabloları ağ olmadan kullanılamaz.", "uk": "Списки лідерів недоступні без мережі.",
  "uz": "Etakchilar ro'yxati tarmoqsiz mavjud emas.", "vi": "Bảng xếp hạng không khả dụng khi ngoại tuyến.",
  "zh": "排行榜在离线状态下不可用。"
},
"leaderboardClose": { "ja": "戻る", "ka": "გამოსვლა", "kk": "ШЫҒУ", "nl": "TERUG", "pl": "WYJŚCIE", "pt": "SAIR",
  "ro": "IEȘIRE", "ru": "ВЫХОД", "sk": "ODÍSŤ", "sr": "ИЗЛАЗ", "th": "ออก", "tk": "ÇYKYŞ",
  "tr": "ÇIKIŞ", "uk": "ВИХІД", "uz": "CHIQISH", "vi": "THOÁT", "zh": "退出","ar": "خروج", "az": "ÇIXIŞ", "be": "ВЫХАД", "bg": "ИЗХОД", "ca": "SORTIR", "cs": "ОDЕЈDОUТ",
  "de": "BEENDEN", "en": "BACK", "es": "SALIR", "fa": "خروج", "fr": "QUITTER", "he": "יציאה",
  "hi": "बाहर निकलें", "hu": "KILÉPÉS", "hy": "ԵԼՔ", "id": "KELUAR", "it": "ESCI"
},
"leaderboardEmptyLine1": {
  "ar": "الجدول فارغ.", "az": "CƏDVƏL BOŞDUR.", "be": "ТАБЛІЦА ПУСТАЯ.", "bg": "ТАБЛИЦАТА Е ПРАЗНА.", "ca": "LA TAULA ESTÀ BUIDA.", "cs": "TABULKA JE PRÁZDNÁ.", "de": "TABELLE IST LEER.", "en": "BOARD IS EMPTY.", "es": "LA TABLA ESTÁ VACÍA.", "fa": "جدول خالی است.", "fr": "TABLEAU VIDE.", "he": "הלוח ריק.", "hi": "तालिका खाली है।", "hu": "A TÁBLÁZAT ÜRES.", "hy": "ԱՂՅՈՒՍԱԿԸ ԴԱՏԱՐԿ Է։", "id": "PAPAN KOSONG.", "it": "IL TABELLONE È VUOTO.", "ja": "ボードは空です。", "ka": "ტაბულა ცარიელია.", "kk": "КЕСТЕ БОС.", "nl": "BORD IS LEEG.", "pl": "TABELA JEST PUSTA.", "pt": "A TABELA ESTÁ VAZIA.", "ro": "TABELUL ESTE GOL.", "ru": "ТАБЛИЦА ПУСТА.", "sk": "TABUĽKA JE PRÁZDNA.", "sr": "ТАБЕЛА ЈЕ ПРАЗНА.", "th": "กระดานว่างเปล่า", "tk": "TABLISA BOŞ.", "tr": "TABLO BOŞ.", "uk": "ТАБЛИЦЯ ПОРОЖНЯ.", "uz": "JADVAL BO'SH.", "vi": "BẢNG TRỐNG.", "zh": "排行榜为空。"
},
"leaderboardEmptyLine2": {
  "ar": "كن الأول!", "az": "BİRİNCİ OLUN!", "be": "СТАНЬЦЕ ПЕРШЫМ!", "bg": "БЪДЕТЕ ПЪРВИЯТ!", "ca": "SIGUES EL PRIMER!", "cs": "BUĎTE PRVNÍ!", "de": "SEI DER ERSTE!", "en": "BE THE FIRST!", "es": "¡SÉ EL PRIMERO!", "fa": "اولین نفر باشید!", "fr": "SOYEZ LE PREMIER !", "he": "היו הראשונים!", "hi": "पहले बनें!", "hu": "LEGYEN ÖN AZ ELSŐ!", "hy": "ԵՂԵ՛Ք ԱՌԱՋԻՆԸ։", "id": "JADILAH YANG PERTAMA!", "it": "SII IL PRIMO!", "ja": "最初の一人になろう！", "ka": "იყავით პირველი!", "kk": "БІРІНШІ БОЛЫҢЫЗ!", "nl": "WEES DE EERSTE!", "pl": "BĄDŹ PIERWSZY!", "pt": "SEJA O PRIMEIRO!", "ro": "FII PRIMUL!", "ru": "СТАНЬТЕ ПЕРВЫМ!", "sk": "BUĎTE PRVÝ!", "sr": "БУДИТЕ ПРВИ!", "th": "เป็นคนแรกเลย!", "tk": "BIRINJI BOLUŇ!", "tr": "BİRİNCİ OLUN!", "uk": "СТАНЬТЕ ПЕРШИМ!", "uz": "BIRINCHI BO'LING!", "vi": "HÃY LÀ NGƯỜI ĐẦU TIÊN!", "zh": "成为第一名！"
},
"leaderboardError": {
  "ar": "خطأ في التحميل", "az": "YÜKLƏMƏ XƏTASI", "be": "ПАМЫЛКА ЗАГРУЗКІ", "bg": "ГРЕШКА ПРИ ЗАРЕЖДАНЕ", "ca": "ERROR DE CÀRREGA", "cs": "CHYBA NAČÍTÁNÍ", "de": "LADEFEHLER", "en": "LOADING ERROR", "es": "ERROR DE CARGA", "fa": "خطا در بارگذاری", "fr": "ERREUR DE CHARGEMENT", "he": "שגיאת טעינה", "hi": "लोडिंग त्रुटि", "hu": "BETÖLTÉSI HIBA", "hy": "ԲԵՌՆՄԱՆ ՍԽԱԼ", "id": "KESALAHAN MEMUAT", "it": "ERRORE DI CARICAMENTO", "ja": "読み込みエラー", "ka": "ჩატვირთვის შეცდომა", "kk": "ЖҮКТЕУ ҚАТАСЫ", "nl": "LAADFOUT", "pl": "BŁĄD ŁADOWANIA", "pt": "ERRO DE CARREGAMENTO", "ro": "EROARE DE ÎNCĂRCARE", "ru": "ОШИБКА ЗАГРУЗКИ", "sk": "CHYBA NAČÍTANIA", "sr": "ГРЕШКА ПРИ УЧИТАВАЊУ", "th": "เกิดข้อผิดพลาดในการโหลด", "tk": "ÝÜKLENME ÝALŇYŞLYGY", "tr": "YÜKLEME HATASI", "uk": "ПОМИЛКА ЗАВАНТАЖЕННЯ", "uz": "YUKLASH HATOSI", "vi": "LỖI TẢI XUỐNG", "zh": "加载错误"
},
"leaderboardLoading": {
  "ar": "جاري التحميل...", "az": "CƏDVƏL YÜKLƏNİR...", "be": "ЗАГРУЗКА ТАБЛІЦЫ...", "bg": "ЗАРЕЖДАНЕ НА ТАБЛИЦАТА...", "ca": "CARREGANT LA TAULA...", "cs": "NAČÍTÁNÍ TABULKY...", "de": "TABELLE WIRD GELADEN...", "en": "LOADING...", "es": "CARGANDO TABLA...", "fa": "بارگذاری جدول...", "fr": "CHARGEMENT...", "he": "טוען לוח...", "hi": "तालिका लोड हो रही है...", "hu": "TÁBLÁZAT BETÖLTÉSE...", "hy": "ԱՂՅՈՒՍԱԿԸ ԲԵՌՆՎՈՒՄ Է...", "id": "MEMUAT PAPAN...", "it": "CARICAMENTO...", "ja": "読み込み中...", "ka": "ტაბულა იტვირთება...", "kk": "КЕСТЕ ЖҮКТЕЛУДЕ...", "nl": "LADEN...", "pl": "ŁADOWANIE TABELI...", "pt": "CARREGANDO...", "ro": "SE ÎNCARCĂ TABELUL...", "ru": "ЗАГРУЗКА ТАБЛИЦЫ...", "sk": "NAČÍTANIE TABUĽKY...", "sr": "УЧИТАВАЊЕ ТАБЕЛЕ...", "th": "กำลังโหลดกระดาน...", "tk": "TABLISA ÝÜKLENÝÄR...", "tr": "TABLO YÜKLENİYOR...", "uk": "ЗАВАНТАЖЕННЯ ТАБЛИЦІ...", "uz": "JADVAL YUKLANMOQDA...", "vi": "ĐANG TẢI BẢNG...", "zh": "正在加载..."
},
    "title": {
      "ar": "تيتريس",
      "az": "TETRİS",
      "be": "ТЭТРЫС",
      "bg": "ТЕТРА",
      "ca": "TETRA",
      "cs": "TETRA",
      "de": "TETRA",
      "en": "TETRA",
      "es": "TETRA",
      "fa": "خانه سازی",
      "fr": "TETRA",
      "he": "טטריס",
      "hi": "टेट्रिस",
      "hu": "TETRAZ",
      "hy": "ՏԵՏՐԻՍ",
      "id": "TETRA",
      "it": "TETRA",
      "ja": "テトリス",
      "ka": "ტეტრისი",
      "kk": "ТЕТРА",
      "nl": "TETRA",
      "pl": "TETRA",
      "pt": "TETRA",
      "ro": "TETRA",
      "ru": "ТЕТРА",
      "sk": "TETRA",
      "sr": "ТЕТРА",
      "th": "เททริส",
      "tk": "TETRA",
      "tr": "TETRİS",
      "uk": "ТЕТРІС",
      "uz": "TETRA",
      "vi": "TETRA",
      "zh": "俄罗斯方块"
    },

    "titleCenter": {
      "ar": "تيتريس",
      "az": "TETRİS",
      "be": "ТЭТРЫС",
      "bg": "ТЕТРА",
      "ca": "TETRA",
      "cs": "TETRA",
      "de": "TETRA",
      "en": "TETRA",
      "es": "TETRA",
      "fa": "خانه سازی<br />TETRA",
      "fr": "TETRA",
      "he": "טטריס",
      "hi": "टेट्रिस<br />TETRA",
      "hu": "TETRAZ",
      "hy": "ՏԵՏՐԻՍ",
      "id": "TETRA",
      "it": "TETRA",
      "ja": "テトリス",
      "ka": "ტეტრისი<br />TETRA",
      "kk": "ТЕТРА",
      "nl": "TETRA",
      "pl": "TETRA",
      "pt": "TETRA",
      "ro": "TETRA",
      "ru": "ТЕТРА",
      "sk": "TETRA",
      "sr": "ТЕТРА",
      "th": "เททริส<br />TETRA",
      "tk": "TETRA",
      "tr": "TETRİS",
      "uk": "ТЕТРІС",
      "uz": "TETRA",
      "vi": "TETRA",
      "zh": "俄罗斯方块<br />TETRA"
    },

    "point": {
      "ar": "نقاط",
      "az": "Xal",
      "be": "Ачкі",
      "bg": "Точки",
      "ca": "Punts",
      "cs": "Body",
      "de": "Punkte",
      "en": "Point",
      "es": "Puntos",
      "fa": "امتیاز",
      "fr": "Score",
      "he": "ניקוד",
      "hi": "अंक",
      "hu": "Pont",
      "hy": "Միավոր",
      "id": "Poin",
      "it": "Punti",
      "ja": "得点",
      "ka": "ქულა",
      "kk": "Ұпай",
      "nl": "Punten",
      "pl": "Punkty",
      "pt": "Pontos",
      "ro": "Puncte",
      "ru": "Очки",
      "sk": "Body",
      "sr": "Поени",
      "th": "คะแนน",
      "tk": "Oçko",
      "tr": "Puan",
      "uk": "Очки",
      "uz": "Ochko",
      "vi": "Điểm",
      "zh": "得分"
    },
     "highestScore": {
         "ar": "رقم",
      "az": "Rekord",
      "be": "Рэкорд",
      "bg": "Рекорд",
      "ca": "Rècord",
      "cs": "Rekord",
      "de": "Rekord",
      "en": "Max",
      "es": "Récord",
      "fa": "حداکثر",
      "fr": "Max",
      "he": "שיא",
      "hi": "टॉप",
      "hu": "Rekord",
      "hy": "Ռեկորդ",
      "id": "Rekor",
      "it": "Record",
      "ja": "最高",
      "ka": "რეკორდი",
      "kk": "Рекорд",
      "nl": "Record",
      "pl": "Rekord",
      "pt": "Recorde",
      "ro": "Record",
      "ru": "Рекорд",
      "sk": "Rekord",
      "sr": "Рекорд",
      "th": "สูงสุด",
      "tk": "Rekord",
      "tr": "Rekor",
      "uk": "Рекорд",
      "uz": "Rekord",
      "vi": "Cao",
      "zh": "最高"
  
    },
    "lastRound": {
      "ar": "سابق",
      "az": "Əvvəl",
      "be": "Раней",
      "bg": "Предишен",
      "ca": "Anterior",
      "cs": "Minulé",
      "de": "Vorher",
      "en": "Last",
      "es": "Anterior",
      "fa": "قبلی",
      "fr": "Dernier",
      "he": "קודם",
      "hi": "पिछला",
      "hu": "Előző",
      "hy": "Նախորդ",
      "id": "Sebelum",
      "it": "Ultimo",
      "ja": "前回",
      "ka": "წინა",
      "kk": "Алдыңғы",
      "nl": "Vorige",
      "pl": "Poprzednia",
      "pt": "Anterior",
      "ro": "Anterioară",
      "ru": "Ранее",
      "sk": "Minulé",
      "sr": "Претходна",
      "th": "ก่อน",
      "tk": "Öňki",
      "tr": "Önceki",
      "uk": "Попередній",
      "uz": "Oldingi",
      "vi": "Trước",
      "zh": "上轮"
    },
    "cleans": {
      "ar": "مسح",
      "az": "Təmizləmə",
      "be": "Ачышчана",
      "bg": "Почистени",
      "ca": "Neteja",
      "cs": "Vyčištěno",
      "de": "Gereinigt",
      "en": "Cleans",
      "es": "Líneas",
      "fa": "پاک",
      "fr": "Lignes",
      "he": "נוקה",
      "hi": "साफ",
      "hu": "Tisztítás",
      "hy": "Մաքրում",
      "id": "Bersih",
      "it": "Pulizie",
      "ja": "消去",
      "ka": "გასუფთ",
      "kk": "Тазарту",
      "nl": "Gepoetst",
      "pl": "Czyste",
      "pt": "Limpezas",
      "ro": "Curățări",
      "ru": "Очищено",
      "sk": "Vyčistené",
      "sr": "Очишћено",
      "th": "เคลียร์",
      "tk": "Arassalandy",
      "tr": "Temizlik",
      "uk": "Очищено",
      "uz": "Tozalandi",
      "vi": "Xóa",
      "zh": "消除"
    },
       "level": {
      "ar": "المستوى",
      "az": "Səviyyə",
      "be": "Узровень",
      "bg": "Ниво",
      "ca": "Nivell",
      "cs": "Úroveň",
      "de": "Stufe",
      "en": "Level",
      "es": "Nivel",
      "fa": "سطح",
      "fr": "Difficulté",
      "he": "רמה",
      "hi": "स्तर",
      "hu": "Szint",
      "hy": "Մակարդակ",
      "id": "Level",
      "it": "Livello",
      "ja": "レベル",
      "ka": "დონე",
      "kk": "Деңгей",
      "nl": "Niveau",
      "pl": "Poziom",
      "pt": "Nível",
      "ro": "Nivel",
      "ru": "Уровень",
      "sk": "Úroveň",
      "sr": "Ниво",
      "th": "ระดับ",
      "tk": "Dereje",
      "tr": "Seviye",
      "uk": "Рівень",
      "uz": "Daraja",
      "vi": "Cấp độ",
      "zh": "级别"
    },
      "startLine": {
      "ar": "بداية",
      "az": "Başlan",
      "be": "Старт",
      "bg": "Старт",
      "ca": "Inici",
      "cs": "Start",
      "de": "Start",
      "en": "Start",
      "es": "Inicio",
      "fa": "شروع",
      "fr": "Départ",
      "he": "התחלה",
      "hi": "शुरू",
      "hu": "Kezdő",
      "hy": "Սկիզբ",
      "id": "Mulai",
      "it": "Partenza",
      "ja": "開始",
      "ka": "საწყისი",
      "kk": "Бастау",
      "nl": "Start",
      "pl": "Start",
      "pt": "Início",
      "ro": "Start",
      "ru": "Начало",
      "sk": "Štart",
      "sr": "Почетак",
      "th": "เริ่ม",
      "tk": "Başla",
      "tr": "Başlangıç",
      "uk": "Старт",
      "uz": "Boshlash",
      "vi": "Bắt đầu",
      "zh": "起始"
    },
    "next": {
      "ar": "التالي",
      "az": "Növbəti",
      "be": "Наступны",
      "bg": "Следващ",
      "ca": "Següent",
      "cs": "Další",
      "de": "Nächste",
      "en": "Next",
      "es": "Siguiente",
      "fa": "بعدی",
      "fr": "Prochain",
      "he": "הבא",
      "hi": "अगला",
      "hu": "Következő",
      "hy": "Հաջորդ",
      "id": "Selanjutnya",
      "it": "Prossimo",
      "ja": "次",
      "ka": "შემდეგი",
      "kk": "Келесі",
      "nl": "Volgende",
      "pl": "Następny",
      "pt": "Próximo",
      "ro": "Următorul",
      "ru": "Дальше",
      "sk": "Ďalší",
      "sr": "Следећи",
      "th": "ถัดไป",
      "tk": "Indiki",
      "tr": "Sonraki",
      "uk": "Далі",
      "uz": "Keyingi",
      "vi": "Tiếp theo",
      "zh": "下一个"
    },
    "pause": {
      "ar": "وقت",
      "az": "Dayan",
      "be": "Паўза",
      "bg": "Пауза",
      "ca": "Pausa",
      "cs": "Pauza",
      "de": "Pause",
      "en": "Pause",
      "es": "Pausa",
      "fa": "ایست",
      "fr": "Pause",
      "he": "עצור",
      "hi": "रोको",
      "hu": "Szünet",
      "hy": "Դադար",
      "id": "Jeda",
      "it": "Pausa",
      "ja": "停止",
      "ka": "პაუზა",
      "kk": "Пауза",
      "nl": "Pauze",
      "pl": "Pauza",
      "pt": "Pausa",
      "ro": "Pauză",
      "ru": "Пауза",
      "sk": "Pauza",
      "sr": "Пауза",
      "th": "หยุด",
      "tk": "Pauza",
      "tr": "Dur",
      "uk": "Пауза",
      "uz": "Pauza",
      "vi": "Tạm",
      "zh": "暂停"
    },
    
       "sound": {
      "ar": "صوت",
      "az": "Səs",
      "be": "Гук",
      "bg": "Звук",
      "ca": "So",
      "cs": "Zvuk",
      "de": "Sound",
      "en": "Sound",
      "es": "Sonido",
      "fa": "صدا",
      "fr": "Sonore",
      "he": "צליל",
      "hi": "ध्वनि",
      "hu": "Hang",
      "hy": "Ձայն",
      "id": "Suara",
      "it": "Suono",
      "ja": "サウンド",
      "ka": "ხმა",
      "kk": "Дыбыс",
      "nl": "Geluid",
      "pl": "Dźwięk",
      "pt": "Som",
      "ro": "Sunet",
      "ru": "Звук",
      "sk": "Zvuk",
      "sr": "Звук",
      "th": "เสียง",
      "tk": "Ses",
      "tr": "Ses",
      "uk": "Звук",
      "uz": "Ovoz",
      "vi": "Âm thanh",
      "zh": "音效"
    },
    "reset": {
      "ar": "إعادة",
      "az": "Sıfır",
      "be": "Скід",
      "bg": "Нула",
      "ca": "Rein",
      "cs": "Reset",
      "de": "Reset",
      "en": "Reset",
      "es": "Rein",
      "fa": "ریست",
      "fr": "Reset",
      "he": "איפוס",
      "hi": "रीसेट",
      "hu": "Reset",
      "hy": "Վերա",
      "id": "Reset",
      "it": "Reset",
      "ja": "リセ",
      "ka": "გადატ",
      "kk": "Қалпы",
      "nl": "Reset",
      "pl": "Reset",
      "pt": "Rein",
      "ro": "Reset",
      "ru": "Сброс",
      "sk": "Reset",
      "sr": "Ресет",
      "th": "รีเซ",
      "tk": "Sıfır",
      "tr": "Sıfır",
      "uk": "Скид",
      "uz": "Qayta",
      "vi": "Đặt",
      "zh": "重置"
    },
    "rotation": {
      "ar": "دوران",
      "az": "Fırlanma",
      "be": "Паварот",
      "bg": "Завъртане",
      "ca": "Rotació",
      "cs": "Rotace",
      "de": "Drehung",
      "en": "Rotation",
      "es": "Rotación",
      "fa": "چرخش",
      "fr": "Rotation",
      "he": "סיבוב",
      "hi": "घुमाव",
      "hu": "Forgatás",
      "hy": "Պտույտ",
      "id": "Rotasi",
      "it": "Rotazione",
      "ja": "回転",
      "ka": "ბრუნვა",
      "kk": "Айналу",
      "nl": "Rotatie",
      "pl": "Obrót",
      "pt": "Rotação",
      "ro": "Rotație",
      "ru": "Поворот",
      "sk": "Otočenie",
      "sr": "Ротација",
      "th": "หมุน",
      "tk": "Aýlanma",
      "tr": "Döndürme",
      "uk": "Обертання",
      "uz": "Aylantirish",
      "vi": "Xoay",
      "zh": "旋转"
    },
    "left": {
      "ar": "يسار",
      "az": "Sol",
      "be": "Налева",
      "bg": "Наляво",
      "ca": "Esquerra",
      "cs": "Doleva",
      "de": "Links",
      "en": "Left",
      "es": "Izquierda",
      "fa": "چپ",
      "fr": "Gauche",
      "he": "שמאלה",
      "hi": "बाएँ",
      "hu": "Balra",
      "hy": "Ձախ",
      "id": "Kiri",
      "it": "Sinistra",
      "ja": "左",
      "ka": "მარცხნივ",
      "kk": "Солға",
      "nl": "Links",
      "pl": "Lewo",
      "pt": "Esquerda",
      "ro": "Stânga",
      "ru": "Влево",
      "sk": "Doľava",
      "sr": "Лево",
      "th": "ซ้าย",
      "tk": "Çep",
      "tr": "Sol",
      "uk": "Вліво",
      "uz": "Chapga",
      "vi": "Trái",
      "zh": "左移"
    },
    "right": {
      "ar": "يمين",
      "az": "Sağ",
      "be": "Направа",
      "bg": "Надясно",
      "ca": "Dreta",
      "cs": "Doprava",
      "de": "Rechts",
      "en": "Right",
      "es": "Derecha",
      "fa": "راست",
      "fr": "Droite",
      "he": "ימינה",
      "hi": "दाएँ",
      "hu": "Jobbra",
      "hy": "Աջ",
      "id": "Kanan",
      "it": "Destra",
      "ja": "右",
      "ka": "მარჯვნივ",
      "kk": "Оңға",
      "nl": "Rechts",
      "pl": "Prawo",
      "pt": "Direita",
      "ro": "Dreapta",
      "ru": "Вправо",
      "sk": "Doprava",
      "sr": "Десно",
      "th": "ขวา",
      "tk": "Sağ",
      "tr": "Sağ",
      "uk": "Вправо",
      "uz": "O‘ngga",
      "vi": "Phải",
      "zh": "右移"
    },
    "down": {
      "ar": "أسفل",
      "az": "Aşağı",
      "be": "Уніз",
      "bg": "Надолу",
      "ca": "Avall",
      "cs": "Dolů",
      "de": "Runter",
      "en": "Down",
      "es": "Abajo",
      "fa": "پایین",
      "fr": "Bas",
      "he": "למטה",
      "hi": "नीचे",
      "hu": "Le",
      "hy": "Ներքև",
      "id": "Bawah",
      "it": "Giù",
      "ja": "下",
      "ka": "ქვემოთ",
      "kk": "Төмен",
      "nl": "Omlaag",
      "pl": "Dół",
      "pt": "Baixo",
      "ro": "Jos",
      "ru": "Вниз",
      "sk": "Dole",
      "sr": "Доле",
      "th": "ลง",
      "tk": "Aşak",
      "tr": "Aşağı",
      "uk": "Вниз",
      "uz": "Pastga",
      "vi": "Xuống",
      "zh": "下移"
    },
    "drop": {
      "ar": "إسقاط",
      "az": "Düşür",
      "be": "Упусціць",
      "bg": "Пускане",
      "ca": "Caure",
      "cs": "Pustit",
      "de": "Fallen",
      "en": "Drop",
      "es": "Soltar",
      "fa": "سقوط",
      "fr": "Tomber",
      "he": "הפלה",
      "hi": "गिराएँ",
      "hu": "Ledob",
      "hy": "Գցել",
      "id": "Jatuh",
      "it": "Cadere",
      "ja": "ドロップ",
      "ka": "ჩაგდება",
      "kk": "Түсіру",
      "nl": "Vallen",
      "pl": "Upuść",
      "pt": "Soltar",
      "ro": "Aruncă",
      "ru": "Уронить",
      "sk": "Pustiť",
      "sr": "Спусти",
      "th": "วาง",
      "tk": "Taşla",
      "tr": "Bırak",
      "uk": "Впустити",
      "uz": "Tashla",
      "vi": "Thả",
      "zh": "掉落"
    },
    "rateGame": {
  "ar": "قيم اللعبة!",
  "az": "Oyunu dəyərləndir!",
  "be": "Ацаніце гульню!",
  "bg": "Оценете играта!",
  "ca": "Valora el joc!",
  "cs": "Ohodnoťte hru!",
  "de": "Bewerte das Spiel!",
  "en": "Rate the game!",
  "es": "¡Califica el juego!",
  "fa": "به بازی امتیاز دهید!",
  "fr": "Notez le jeu !",
  "he": "דרג את המשחק!",
  "hi": "गेम को रेट करें!",
  "hu": "Értékeld a játékot!",
  "hy": "Գնահատեք խաղը!",
  "id": "Nilai gamenya!",
  "it": "Valuta il gioco!",
  "ja": "ゲームを評価！",
  "ka": "შეაფასე თამაში!",
  "kk": "Ойынды бағала!",
  "nl": "Beoordeel de game!",
  "pl": "Oceń grę!",
  "pt": "Avalie o jogo!",
  "ro": "Evaluează jocul!",
  "ru": "Оцените игру!",
  "sk": "Ohodnoťte hru!",
  "sr": "Оцените игру!",
  "th": "ให้คะแนนเกม!",
  "tk": "Oýuny bahala!",
  "tr": "Oyunu değerlendir!",
  "uk": "Оцініть гру!",
  "uz": "O‘yinni baholang!",
  "vi": "Đánh giá trò chơi!",
  "zh": "给游戏评分！"
},
"rateGameText": {
  "ar": "إذا أعجبك تيتريس، قيم التطبيق في المتجر. سيساعدنا ذلك على التحسن!",
  "az": "TETRA xoşunuza gəlirsə, tətbiq mağazasında qiymətləndirin. Bu, daha yaxşı olmağımıza kömək edəcək!",
  "be": "Калі вам падабаецца Тэтрыс, пастаўце ацэнку ў краме прыкладанняў. Гэта дапаможа нам стаць лепш!",
  "bg": "Ако харесвате ТЕТРА, оценете приложението в магазина. Това ще ни помогне да станем по-добри!",
  "ca": "Si t'agrada el TETRA, valora l'aplicació a la botiga. Això ens ajudarà a millorar!",
  "cs": "Pokud se vám TETRA líbí, ohodnoťte aplikaci v obchodě. Pomůže nám to se zlepšit!",
  "de": "Wenn dir TETRA gefällt, bewerte die App im Store. Das hilft uns, besser zu werden!",
  "en": "If you like TETRA, rate the app in the store. It will help us become better!",
  "es": "Si te gusta TETRA, califica la aplicación en la tienda. ¡Nos ayudará a mejorar!",
  "fa": "اگر تتریس را دوست دارید، در فروشگاه به برنامه امتیاز دهید. این به ما کمک میکند بهتر شویم!",
  "fr": "Si vous aimez TETRA, notez l'application dans le magasin. Cela nous aidera à nous améliorer !",
  "he": "אם אתה אוהב טטריס, דרג את האפליקציה בחנות. זה יעזור לנו להשתפר!",
  "hi": "अगर आपको टेट्रिस पसंद है, तो स्टोर में ऐप को रेट करें। इससे हमें बेहतर बनने में मदद मिलेगी!",
  "hu": "Ha tetszik a TETRA, értékeld az alkalmazást a boltban. Ez segít jobbá válnunk!",
  "hy": "Եթե ձեզ դուր է գալիս Տետրիսը, գնահատեք հավելվածը խանութում: Դա կօգնի մեզ դառնալ ավելի լավը:",
  "id": "Jika Anda menyukai TETRA, beri nilai aplikasi di toko. Ini akan membantu kami menjadi lebih baik!",
  "it": "Se ti piace TETRA, valuta l'app nel negozio. Ci aiuterà a migliorare!",
  "ja": "テトリスが気に入ったら、ストアでアプリを評価してください。より良くなるために役立ちます！",
  "ka": "თუ მოგწონთ ტეტრისი, შეაფასეთ აპლიკაცია მაღაზიაში. ეს დაგვეხმარება გავუმჯობესდეთ!",
  "kk": "Егер сізге ТЕТРА ұнаса, қосымшаны дүкенде бағалаңыз. Бұл бізге жақсаруға көмектеседі!",
  "nl": "Als je TETRA leuk vindt, beoordeel de app dan in de winkel. Het helpt ons beter te worden!",
  "pl": "Jeśli lubisz TETRA, oceń aplikację w sklepie. To pomoże nam stać się lepszymi!",
  "pt": "Se você gosta do TETRA, avalie o aplicativo na loja. Isso nos ajudará a melhorar!",
  "ro": "Dacă îți place TETRA, evaluează aplicația în magazin. Ne va ajuta să devenim mai buni!",
  "ru": "Если вам нравится ТЕТРА, поставьте оценку в магазине приложений. Это поможет нам стать лучше!",
  "sk": "Ak sa vám páči TETRA, ohodnoťte aplikáciu v obchode. Pomôže nám to zlepšiť sa!",
  "sr": "Ако вам се свиђа ТЕТРА, оцените апликацију у продавници. То ће нам помоћи да постанемо бољи!",
  "th": "ถ้าคุณชอบเททริส โปรดให้คะแนนแอปในร้านค้า มันจะช่วยให้เราดีขึ้น!",
  "tk": "TETRA siziň göwnüňize ýarasa, programmany dükanda bahalaň. Bu biziň has gowy bolmagymyza kömek eder!",
  "tr": "TETRA'i beğendiyseniz, uygulamayı mağazada değerlendirin. Bu, daha iyi olmamıza yardımcı olacak!",
  "uk": "Якщо вам подобається Тетріс, поставте оцінку в магазині застосунків. Це допоможе нам стати кращими!",
  "uz": "Agar sizga TETRA yoqsa, ilovani do'konda baholang. Bu bizga yaxshilanishga yordam beradi!",
  "vi": "Nếu bạn thích TETRA, hãy đánh giá ứng dụng trong cửa hàng. Điều này sẽ giúp chúng tôi tốt hơn!",
  "zh": "如果您喜欢俄罗斯方块，请在应用商店中给应用评分。这将帮助我们变得更好！"
}
  }
};

const blockShape = {
  // I (палка) — 3 блока
  I: [[1, 1, 1]],  
  // L (уголок) — 3 блока
  L: [[1, 0], [1, 1]],  
  // J (зеркальный уголок) — 3 блока
  J: [[0, 1], [1, 1]],  
  // Z (зигзаг) — 4 блока
  Z: [[1, 1, 0], [0, 1, 1]],  
  // S (зеркальный зигзаг) — 4 блока
  S: [[0, 1, 1], [1, 1, 0]],  
  // O (квадрат) — 4 блока
  O: [[1, 1], [1, 1]],  
  // T (крест) — 5 блоков
  T: [[0, 1, 0], [1, 1, 1], [0, 1, 0]],
};

const origin = {
  I: [[0, 0]],        // прямая 3×1 — вращается нормально
  L: [[0, 0]],        // уголок 3 блока
  J: [[0, 0]],        // зеркальный уголок
  Z: [[0, 0]],        // зигзаг
  S: [[0, 0]],        // зеркальный зигзаг
  O: [[0, 0]],        // квадрат — не вращается
  T: [[0, 0]],        // крест — не вращается
};

const blockType = Object.keys(blockShape);

const speeds = [800, 650, 500, 450, 370, 300, 250, 200, 160, 120];
//const speeds = [800, 650, 500, 370, 250, 160];

const delays = [50, 60, 70, 80, 90, 100];

const fillLine = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

const blankLine = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

const blankMatrix = (() => {
  const matrix = [];
  for (let i = 0; i < 20; i++) {
    matrix.push(List(blankLine));
  }
  return List(matrix);
})();

const clearPoints = [1, 2, 3, 4];

const StorageKey = 'REACT_TETRIS';

const lastRecord = (() => {
  let data = localStorage.getItem(StorageKey);
  if (!data) {
    return false;
  }
  try {
    if (window.btoa) {
      data = atob(data);
    }
    data = decodeURIComponent(data);
    data = JSON.parse(data);
  } catch (e) {
    if (window.console || window.console.error) {
      window.console.error('Ошибка чтения записи:', e);
    }
    return false;
  }
  return data;
})();

const maxPoint = 999999;

const transform = (function () {
  const trans = ['transform', 'webkitTransform', 'msTransform', 'mozTransform', 'oTransform'];
  const body = document.body;
  return trans.filter((e) => body.style[e] !== undefined)[0];
}());

const eachLines = 50;

const getParam = (param) => {
  const r = new RegExp(`\\?(?:.+&)?${param}=(.*?)(?:&.*)?$`);
  const m = window.location.toString().match(r);
  return m ? decodeURI(m[1]) : '';
};

// 1. Создаем внутренний объект для хранения текущего языка
const langStorage = {  value: (() => { if (typeof navigator !== 'undefined') {
      const browserLang = (navigator.language || navigator.userLanguage).substring(0, 2).toLowerCase();
      return i18n.lan.indexOf(browserLang) !== -1 ? browserLang : i18n.default;    }   return i18n.default; })()};
// 2. Функция для ВК, которая будет менять язык «на лету»
const changeLanguageFromVK = (vkLang) => {  if (!vkLang) return;  const cleanLang = vkLang.substring(0, 2).toLowerCase();
  if (i18n.lan.indexOf(cleanLang) !== -1) {    langStorage.value = cleanLang;    try {      document.title = i18n.data.title[cleanLang];
    } catch (e) {} }};
// 3. Формируем объект экспорта, где 'lan' ведет себя как обычная строка (свойство)
module.exports = {  
  blockShape,
  origin,
  blockType,
  speeds,
  delays,
  fillLine,
  blankLine,
  blankMatrix,
  clearPoints,
  StorageKey,
  lastRecord,
  maxPoint,
  eachLines,
  transform,
   changeLanguageFromVK,
  // Экспортируем строго внутренний массив данных, как и требовала оригинальная игра!
  i18n: i18n.data, 
  // Геттер превращает вызов свойства в динамический возврат строки
  get lan() {
    return langStorage.value;
  },
  changeLanguageFromVK
};

try {
  // Берём язык напрямую из нашего хранилища langStorage
  const defaultTitleLang = langStorage.value;
  if (i18n.data && i18n.data.title && i18n.data.title[defaultTitleLang]) {
    document.title = i18n.data.title[defaultTitleLang];
  }
} catch (e) {}

// Для динамического обновления фигур
// В const.js, замените существующую функцию updateBlockShape на эту:
export const updateBlockShape = (newShapes) => {  // Очищаем старые фигурки
  Object.keys(blockShape).forEach(key => delete blockShape[key]);  // Добавляем новые
  Object.assign(blockShape, newShapes);  
  // ОЧЕНЬ ВАЖНО: обновляем blockType для генерации следующих фигурок
  blockType.length = 0;  Object.keys(blockShape).forEach(key => blockType.push(key));  
  //console.log('Фигурки обновлены:', Object.keys(blockShape));
 // console.log('Типы для генерации:', blockType);
};
// Объявляем глобально
if (typeof window !== 'undefined') {
  window.blockShapeUpdate = updateBlockShape;
  window.blockShape = blockShape;
  window.blockType = blockType; // Добавляем для доступа из mode.js
}

